# Generated by Django 6.0.4 on 2026-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_created_at_contact_sent_at_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('salesforce', 'Salesforce'), ('tools', 'Tools & DevOps')], default='frontend', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon character', max_length=10, null=True),
        ),
    ]
